### ISSUE TITLE
Help with the server :)

### ISSUE THREAD

**Issue by JayaramR307** [pavviaz/latexOCRserver#1]
Hi,
As I am working on my final year project, I would really like to know how to host this repository to the server. I tried to deploy 
LaTeX-OCR by lukas-blecher on Heroku, but the slug size limit exceeds due to dependency modules. Please recommend the server that you used.
Thank you

**Comment by pavviaz** [comment]
Hello! Actually, I deployed the server on Google Cloud Platform. It gives you a free trial 300$, that you can use on anything you want. Personally, I created a virtual machine with Ubuntu 20.04 LTS, 4 vCPUs and 16 GB memory (may be it's too much for such a project), installed some libraries on VM and this is it. 

Please note, that my repo has some issues (some requirements are missing and some scripts don't work correctly), if you want, contact me in discord (pavviaz#7372) for more details, but anyway I will fix this soon and make a little README file with step-by-step server deployment.

**Comment by JayaramR307** [comment]
Thank you very much :)
I'll try this and let you know if I run into something.
